# file based on https://github.com/slackhq/slack-lints/blob/main/.github/workflows/ci.yml

name: CI

on:
  # Only run push on main
  push:
    branches:
      - master
    paths-ignore:
      - '**/*.md'
  # Always run on PRs
  pull_request:
    branches: [ master ]
  merge_group:

concurrency:
  group: 'ci-${{ github.event.merge_group.head_ref || github.head_ref }}-${{ github.workflow }}'
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@f9c9c575b8b21b6485636a91ffecd10e558c62f6 # v3

      - name: Install JDK
        uses: actions/setup-java@b36c23c0d998641eff861008f374ee103c25ac73 # v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build
        uses: gradle/gradle-build-action@ac2d340dc04d9e1113182899e983b5400c17cda1 # v3
        with:
          arguments: spotlessCheck compileKotlin

      - name: Check
        uses: gradle/gradle-build-action@ac2d340dc04d9e1113182899e983b5400c17cda1 # v3
        with:
          arguments: check --stacktrace

      - name: (Fail-only) Upload build reports
        if: failure()
        uses: actions/upload-artifact@84480863f228bb9747b473957fcc9e309aa96097 # v4
        with:
          name: reports
          path: |
            **/build/reports/**
